### ISSUE TITLE
policy/signature vs. key?

### ISSUE THREAD

**Issue by lukemelia** [infowrap/filepicker_client#14]
In reading the REST API docs, it seems that it would be acceptable/appropriate use the `key` parameter instead of `policy` and `signature`. Should this gem use that approach, or support it as an option?

**Comment by adafair** [comment]
The "key" param is for passing the API key for the account being used. The "signature" and "policy" params are separate and are passed with calls to ensure you have permission to make them.

That's my understanding of it at least. Can you point me to where you're looking in the documentation?
