### ISSUE TITLE
Key missing from stat calls

### ISSUE THREAD

**Issue by r38y** [infowrap/filepicker_client#6]
It looks like if you have security turned on the key needs to be present for the stat (and maybe other) call. Does it make sense to always include the key for urls that aren't for user's downloading the file?

**Comment by adafair** [comment]
The stat call is actually just a HEAD request to a read URI. The read call uses the same URI but does a GET instead.

I believe at least for these two calls we don't need the key. I've been testing against an account with security enabled, and both calls seem to work fine without the key.

https://developers.inkfilepicker.com/docs/web/#inkblob-contents

It looks like the key is only needed when there is not a specific file being addressed. So, storing a new file would require a key so they know who the file is being uploaded to. When doing anything to an existing file, they should know who the file belongs to in the first place, so the key seems unnecessary when paired with a valid signature and policy.

**Comment by r38y** [comment]
OK, yeah, I think I figured out the problem over the weekend but wasn't 100% sure I had. Thanks for the info and sorry for the distraction :frowning:

**Comment by adafair** [comment]
No worries, never hurts to ask :)
